disabled_rules:
    - class_delegate_protocol
    - colon
    - comma
    - compiler_protocol_init
    - cyclomatic_complexity
    - file_length
    - force_cast
    - force_try
    - for_where
    - function_body_length
    - function_parameter_count
    - identifier_name
    - is_disjoint
    - large_tuple
    - legacy_random
    - line_length
    - multiple_closures_with_trailing_closure
    - nesting
    - no_fallthrough_only
    - operator_whitespace
    - private_over_fileprivate
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_string_enum_value
    - shorthand_operator
    - todo
    - trailing_newline
    - trailing_whitespace
    - type_body_length
    - type_name
    - unneeded_break_in_switch
    - unused_closure_parameter
    - notification_center_detachment
    - non_optional_string_data_conversion

vertical_whitespace:
    max_empty_lines: 2
