#!/bin/bash

clang-format -style=file -i Wikipedia/Code/*.h
clang-format -style=file -i Wikipedia/Code/*.m
clang-format -style=file -i Wikipedia/Code/*.c
clang-format -style=file -i WikipediaUnitTests/Code/*.h
clang-format -style=file -i WikipediaUnitTests/Code/*.m
clang-format -style=file -i WikipediaUnitTests/Code/*.c