#!/bin/bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update && brew install npm clang-format rbenv ruby-build
rbenv install
gem install bundler
bundle install