#!/usr/bin/env ruby

require 'listen'

wd = Dir.pwd

extensions_to_format = [".m", ".h", ".c"]
 
listener = Listen.to(wd + '/Wikipedia/Code', wd + '/WikipediaUnitTests/Code', wd + '/WMFKit') do |modified, added, removed|
  modified_and_added = modified + added
  modified_and_added.each do |path|
    extension = File.extname(path)
    if extensions_to_format.include?(extension)
      puts "Formatting #{path}"
      `clang-format -style=file -i #{path}`
    end
  end
end

listener.start

sleep