enum WMFUserDefaultsKey: String {
    case watchlistFilterSettings = "watchlist-filter-settings"
	case imageRecommendationsOnboarding = "image-recommendations-onboarding"
    case developerSettingsDoNotPostImageRecommendationsEdit = "dev-settings-do-not-post-image-rec-edit"
    case developerSettingsEnableAltTextExperimentForEN = "dev-settings-enable-alt-text-for-en"
    case alwaysShowAltTextEntryPoint = "dev-settings-always-show-alt-text-entry-point"
    case developerSettingsSendAnalyticsToWMFLabs = "dev-settings-send-analytics-to-wmflabs"
    case sawAltTextImageRecommendationsPrompt = "saw-alt-text-image-recommendations-prompt"
    case sawAltTextArticleEditorPrompt = "saw-alt-text-article-editor-prompt"
    case altTextExperimentOnboarding = "alt-text-experiment-onboarding"
    case hasLocallySavedDonations = "donate-history-has-locally-saved-donations"
    case yearInReviewSettingsIsEnabled = "year-in-review-settings-is-enabled"
    case seenYearInReviewFeatureAnnouncement = "year-in-review-feature-announcement"
    case yearInReviewSurveyPresented = "year-in-review-survey-presented"
    case bypassDonation = "bypass-donation"
    case seenYearInReviewIntroSlide = "seen-year-in-review-intro-slide"
}
