
typedef NS_ENUM(NSUInteger, AssetsFileEnum) {
    ASSETS_FILE_UNDEFINED = 0,
    ASSETS_FILE_CONFIG = 1,
    ASSETS_FILE_LANGUAGES = 2,
    ASSETS_FILE_MAINPAGES = 3,
    ASSETS_FILE_CSS = 4,
    ASSETS_FILE_CSS_ABUSE_FILTER = 5,
    ASSETS_FILE_CSS_PREVIEW = 6
};
