import Foundation

/// Autogenerated by Chat GPT
struct Location: Codable, Hashable {
    let name: String?
    let lat: Double
    let long: Double
    
    static let none: Location = .init(name: nil, lat: 0, long: 0)
    
    enum CodingKeys: String, CodingKey {
        case name
        case lat
        case long
    }
}

struct LocationList: Codable {
    let locations: [Location]
}

