
public extension UIColor {

    public static let wmf_lightGray: UIColor = .wmf_color(withHex: 0xdddddd)
    public static let wmf_lightGrayCellBackground: UIColor = .wmf_color(withHex: 0xf8f9fa)
    public static let wmf_sideScrollingArticleCellShadow: UIColor = .wmf_color(withHex: 0xc8ccd1)
    public static let wmf_placeholderLightGray: UIColor = .wmf_color(withHex: 0xf8f8f8)
    public static let wmf_placeholderImageTint: UIColor = .wmf_color(withHex: 0xb2b2b2)
    public static let wmf_placeholderImageBackground: UIColor = .wmf_color(withHex: 0xf4f4f4)
    public static let wmf_articleListBackground: UIColor = .wmf_color(withHex: 0xeaecf0)
    public static let wmf_articleBackground: UIColor = .wmf_articleListBackground
    public static let wmf_inlineTableOfContentsBackground: UIColor = .wmf_color(withHex: 0xf4f5f7)
    public static let wmf_modalTableOfContentsBackground: UIColor = .white
    public static let wmf_modalTableOfContentsSelectionBackground: UIColor = .white
    public static let wmf_inlineTableOfContentsSelectionBackground: UIColor = .wmf_color(withHex: 0xf2f2f2)
    public static let wmf_tableOfContentsSelectionIndicator: UIColor = .wmf_color(withHex: 0x3366cc)
    public static let wmf_tableOfContentsSectionText: UIColor = .wmf_color(withHex: 0x333333)
    public static let wmf_tableOfContentsSubsectionText: UIColor = .wmf_color(withHex: 0x555a5f)
    public static let wmf_exploreSectionHeaderTitle: UIColor = .wmf_customGray
    public static let wmf_exploreSectionHeaderSubTitle: UIColor = .wmf_customGray
    public static let wmf_exploreSectionFooterText: UIColor = .wmf_customGray
    public static let wmf_exploreSectionHeaderIconTint: UIColor = .wmf_customGray
    public static let wmf_exploreSectionHeaderIconBackground: UIColor = .wmf_color(withHex: 0xf5f5f5)
    public static let wmf_exploreSectionHeaderLinkText: UIColor = .wmf_blue
    public static let wmf_blue: UIColor = .wmf_color(withHex: 0x3366cc)
    public static let wmf_darkBlue: UIColor = .wmf_color(withHex: 0x2a4b8d)
    public static let wmf_lightBlue: UIColor = .wmf_color(withHex: 0xeaf3ff)
    public static let wmf_tapHighlight: UIColor = .wmf_color(withHex: 0xeeeeee)
    public static let wmf_nearbyArrow: UIColor = .wmf_color(withHex: 0x00af89)
    public static let wmf_nearbyTick: UIColor = .wmf_color(withHex: 0x00af89, alpha: 0.8)
    public static let wmf_nearbyTitle: UIColor = .black
    public static let wmf_nearbyDescription: UIColor = .wmf_color(withHex: 0x666666)
    public static let wmf_nearbyDistanceBackground: UIColor = .wmf_color(withHex: 0xaaaaaa)
    public static let wmf_999999: UIColor = .wmf_color(withHex: 0x999999)
    public static let wmf_777777: UIColor = .wmf_color(withHex: 0x777777)
    public static let wmf_foundationGray: UIColor = .wmf_color(withHex: 0x7d8389)
    public static let wmf_darkGray: UIColor = .wmf_color(withHex: 0x555a5f)
    public static let wmf_customGray: UIColor = .wmf_color(withHex: 0x9aa0a7)
    public static let wmf_readerWGray: UIColor = .wmf_color(withHex: 0x444444)
    public static let wmf_nearbyDistanceText: UIColor = .white
    public static let wmf_emptyGrayText: UIColor = .wmf_999999
    public static let wmf_navigationGray: UIColor = .wmf_color(withHex: 0x4d4d4b)
    public static let wmf_settingsBackground: UIColor = .wmf_color(withHex: 0xefeff4)
    public static let wmf_green: UIColor = .wmf_color(withHex: 0x00af89)
    public static let wmf_lightGreen: UIColor = .wmf_color(withHex: 0xd5fdf4)
    public static let wmf_welcomeBackgroundGradientTop: UIColor = .wmf_color(withHex: 0x3366cc)
    public static let wmf_welcomeBackgroundGradientBottom: UIColor = .wmf_color(withHex: 0x0af89)
    public static let wmf_primaryLanguageLabelBackground: UIColor = .wmf_color(withHex: 0xcccccc)
    public static let wmf_barButtonItemPopoverMessageBackground: UIColor = .wmf_color(withHex: 0x43464a, alpha: 1.0)
    public static let wmf_referencePopoverBackground: UIColor = .white
    public static let wmf_referencePopoverLink: UIColor = .wmf_color(withHex: 0x3366cc)
    public static let wmf_referencePopoverText: UIColor = .black
    public static let wmf_red: UIColor = .wmf_color(withHex: 0xcc3333)
    public static let wmf_lightRed: UIColor = .wmf_color(withHex: 0xffe7e6)
    public static let wmf_yellow: UIColor = .wmf_color(withHex: 0xffcc33)
    public static let wmf_lightYellow: UIColor = .wmf_color(withHex: 0xfef6e7)
    public static let wmf_orange: UIColor = .wmf_color(withHex: 0xff5b00)
    public static let wmf_authTitle: UIColor = .wmf_color(withHex: 0x72777d)
    public static let wmf_filterDropDownBackground: UIColor = .wmf_color(withHex: 0xf6f6f6)
    public static let wmf_purple: UIColor = .wmf_color(withHex: 0x7f4ab3)
    public static let wmf_lightPurple: UIColor = .wmf_color(withHex: 0xf3e6ff)
}
