#define WIKIGLYPH_X @"\ue95e"
#define WIKIGLYPH_FLAG @"\ue963"
#define WIKIGLYPH_USER_SMILE @"\ue964"
#define WIKIGLYPH_USER_SLEEP @"\ue965"
#define WIKIGLYPH_CC @"\ue969"
#define WIKIGLYPH_PUBLIC_DOMAIN @"\ue96c"
