
#import "WMFArticleListDataSourceTableViewController.h"

NS_ASSUME_NONNULL_BEGIN

@interface WMFSelfSizingArticleListTableViewController : WMFArticleListDataSourceTableViewController

@end

NS_ASSUME_NONNULL_END