# vi: ft=ruby

###################### Available Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/KrauseFx/deliver/blob/master/Deliverfile.md

default_language "en-US"

# Since this file is eval'd, we need to add this file's directory to $LOAD_PATH
$:.unshift File.dirname(__FILE__)
require 'lib/utils.rb'

ENV['DELIVER_WHAT_TO_TEST'] = git_commit_log # automatically store the changelog

automatic_release false

copyright "#{Time.now.year} Wikimedia Foundation"

screenshots_path "./screenshots"

# Specify apple ID explicitly in appropriate lanes to prevent (fragile) iTC API fallback
# See export_apple_id in lib/utils.rb
apple_id ENV['WMF_APPLE_ID']

