# For more information about each property, visit the GitHub documentation: https://github.com/krausefx/deliver
# Everything next to a # is a comment and will be ignored

# hide_transporter_output # remove the '#' in the beginning of the line, to hide the output while uploading

# Set paths to the ipa file
ipa ENV["IPA_OUTPUT_PATH"]
beta_ipa ENV["IPA_OUTPUT_PATH"]


########################################
# App Metadata
########################################

# Set apple_id for Testflight builds
apple_id '981253550'

copyright "#{Time.now.year} Wikimedia Foundation"

# This folder has to include one folder for each language
# More information about automatic screenshot upload:
# https://github.com/KrauseFx/deliver#upload-screenshots-to-itunes-connect

screenshots_path "./screenshots/"

# version '1.2' # you can pass this if you want to verify the version number with the ipa file
config_json_folder './deliver'
