#!/bin/bash
# used on jenkins to update ruby gems

git checkout bundle_update
git pull
bundle update
export GIT_STATUS=`git status --porcelain | grep ^\ [MAD]`
if [ "$GIT_STATUS" ]; then
	git commit -a -m "bundle update"
	git push
	if scripts/pr.rb bundle_update develop "Bundle update"; then
		exit 0
	else
		exit 1
	fi
fi