#!/bin/bash

if [ -z "$SRCROOT" ]
then
    export SRCROOT=`pwd`
fi

export SHA=`shasum -a 256 "$SRCROOT/Cartfile.resolved" |  awk 'match($0, /^[0-9a-f]*/) { print substr($0, RSTART, RLENGTH) }'`
export VERSION=`xcrun swift --version | awk 'match($0, /Apple\ Swift\ version\ [0-9.]*/) { print substr($0, RSTART + 20, RLENGTH - 20) }'`

echo $SHA-$VERSION