#!/bin/bash
# This script is run with every build to ensure the carthage dependencies are up to date

if [ -z "$SRCROOT" ]
then
    export SRCROOT=`pwd`
fi

if [ -z "$CACHEROOT" ]
then
	export CACHEROOT="$SRCROOT/Carthage Cache"
fi

export CARTHAGE="$SRCROOT/Carthage"
export CARTHAGE_SHA=`"$SRCROOT/scripts/carthage_sha"`
export CARTHAGE_CACHE="$CACHEROOT/$CARTHAGE_SHA"

if [ "$1" == "force" ]
then
	echo "Removing prebuilt dependencies..."
	rm -rf "$CARTHAGE"
	rm -rf "$CARTHAGE_CACHE"
fi

echo $CARTHAGE_SHA > "$SRCROOT/Cartfile.hash"
if ! cmp -s "$SRCROOT/Cartfile.hash" "$CARTHAGE/Cartfile.hash"
then
	rm -rf "$CARTHAGE"
	if [ -d "$CARTHAGE_CACHE" ] && [ ! -d "$CARTHAGE" ]
	then
		cp -R "$CARTHAGE_CACHE" "$CARTHAGE"
	else
		brew upgrade carthage 2> /dev/null
		carthage bootstrap --platform iOS --cache-builds 2> /dev/null
		mv "$SRCROOT/Cartfile.hash" "$CARTHAGE/Cartfile.hash"
		if [ -d "$CARTHAGE" ] && [ ! -d "$CARTHAGE_CACHE" ]
		then
			mkdir -p "$CACHEROOT/"
			cp -R "$CARTHAGE" "$CARTHAGE_CACHE"
		fi
	fi
else
	rm "$SRCROOT/Cartfile.hash"
fi