#!/usr/bin/env ruby

file_types = {h: true, m: true, cpp: true, c: true}

`git status --porcelain`.split('\n').each do |line|
  components = line.split(' ')
  next if components.count < 2
  code = components[0]
  next if code == 'D'
  file = components[1]
  extension = file.split('.').last
  next if !file_types[extension.downcase.to_sym]
  `clang-format -style=file -i #{file}`
end