#!/usr/bin/env ruby


def iterate_and_format(dir)
  file_types = {h: true, m: true, cpp: true, c: true}
  Dir.foreach(dir) do |filename|
    next if filename.start_with?('.') || filename.length == 0
    extension = filename.split('.').last
    next if !extension
    next if !file_types[extension.downcase.to_sym]
    puts filename
    full_path = dir + '/' + filename
    begin
      new_file = ''
      skip = true
      File.foreach(full_path) do |line|
        if skip && (/^\/\//.match(line) || line.strip.length == 0)
          
        else
          skip = false
          new_file << line
        end
      end
      File.delete(full_path)
      f = File.new(full_path, 'w')
      f.write(new_file)
      f.close
    rescue Errno::EISDIR
    end
    `clang-format -style=file -i #{full_path}`
  end
end

dirs = ['.']

dirs.each do |dir|
  iterate_and_format(dir)
end

