#!/bin/bash

# Define the source and destination directories
SOURCE=../CodeMirror/wikipedia-ios-codemirror/resources
DEST=../Wikipedia/assets/codemirror

# Check if the source directory is not empty
if [ ! -d "$SOURCE" ] || [ -z "$(ls -A $SOURCE)" ]; then
  echo "Error: $SOURCE directory is missing or empty. Be sure to run the update_submodules script to pull the CodeMirror submodule." >&2
  exit 1
fi

# Remove the destination directory if it exists
if [ -d "$DEST/resources" ]; then
  rm -rf "$DEST/resources"
fi

# Copy the source directory to the destination
cp -r "$SOURCE" "$DEST"

echo "Success: CodeMirror resources copied to $DEST"
