#! /bin/sh

cd "$1"
xcrun extractLocStrings -s WMFLocalizedString -o Wikipedia/iOS\ Native\ Localizations/en.lproj/ Wikipedia/Code/* WMF\ Framework/* InTheNewsNotification/* TopReadWidget/* ContinueReadingWidget/*