import SwiftUI
import UIKit

// MARK: - WMFLottieView
//
// Supports both formats:
//   • .lottie — dotLottie container, loaded via DotLottieFile.named(_:bundle:) (Lottie 4.4+)
//   • .json   — classic Lottie, loaded via LottieAnimation.named(_:bundle:)
//
// Files live in Sources/WMFComponents/Resources/Lotties/ and are resolved
// via Bundle.module (auto-generated by SwiftPM for targets with a resources declaration).

#if canImport(Lottie)
import Lottie

public struct WMFLottieView: UIViewRepresentable {

    public enum LoopMode {
        case loop
        case playOnce
        case bounce

        fileprivate var lottieMode: Lottie.LottieLoopMode {
            switch self {
            case .loop:     return .loop
            case .playOnce: return .playOnce
            case .bounce:   return .autoReverse
            }
        }
    }

    private let animationName: String
    private let loopMode: LoopMode

    public init(animationName: String, loopMode: LoopMode = .loop) {
        self.animationName = animationName
        self.loopMode = loopMode
    }

    // MARK: UIViewRepresentable

    public func makeUIView(context: Context) -> LottieAnimationView {
        let view = LottieAnimationView()
        view.contentMode = .scaleAspectFill
        view.backgroundBehavior = .pauseAndRestore
        loadAnimation(into: view)
        return view
    }

    public func updateUIView(_ uiView: LottieAnimationView, context: Context) {
        if !uiView.isAnimationPlaying {
            uiView.play()
        }
    }

    // MARK: Private

    private func loadAnimation(into view: LottieAnimationView) {
        let bundle = Bundle.module

        // 1. Try .lottie (dotLottie) — DotLottieFile.named loads from bundle, handles subdirectories
        Task { @MainActor in
            do {
                let dotLottie = try await DotLottieFile.named(animationName, bundle: bundle)
                view.loadAnimation(from: dotLottie)
                view.loopMode = loopMode.lottieMode
                view.play()
                return
            } catch {
                // Not a dotLottie — fall through to classic JSON below
            }

            // 2. Fall back to classic .json
            if let animation = LottieAnimation.named(animationName, bundle: bundle) {
                view.animation = animation
                view.loopMode = loopMode.lottieMode
                view.play()
                return
            }

            #if DEBUG
            let allResources = (try? FileManager.default.contentsOfDirectory(atPath: bundle.bundlePath)) ?? []
            print("WMFLottieView: bundle contents: \(allResources.filter { $0.contains(animationName) || $0.hasSuffix(".lottie") })")
            #endif
            assertionFailure("WMFLottieView: no animation found for '\(animationName)' in bundle: \(bundle.bundlePath)")
        }
    }
}

#else

// MARK: - Placeholder (Lottie not linked in this target)

public struct WMFLottieView: View {

    public enum LoopMode { case loop, playOnce, bounce }

    private let animationName: String
    @State private var pulsing = false

    public init(animationName: String, loopMode: LoopMode = .loop) {
        self.animationName = animationName
    }

    public var body: some View {
        GeometryReader { geo in
            ZStack {
                Circle()
                    .fill(RadialGradient(
                        colors: [Color.white.opacity(0.25), Color.white.opacity(0)],
                        center: .center,
                        startRadius: 0,
                        endRadius: geo.size.width * 0.5
                    ))
                    .scaleEffect(pulsing ? 1.15 : 0.85)
                    .opacity(pulsing ? 0.6 : 0.2)
                    .animation(.easeInOut(duration: 2.2).repeatForever(autoreverses: true), value: pulsing)
                #if DEBUG
                Text("[\(animationName)]")
                    .font(.caption2)
                    .foregroundColor(.white.opacity(0.4))
                #endif
            }
        }
        .onAppear { pulsing = true }
    }
}

#endif
