import Foundation

public enum WMFArticleTopic: String, CaseIterable, Sendable {
    case architecture = "architecture"
    case visualArts = "visual-arts"
    case comicsAndAnime = "comics-and-anime"
    case entertainment = "entertainment"
    case fashion = "fashion"
    case books = "books"
    case music = "music"
    case performingArts = "performing-arts"
    case sports = "sports"
    case films = "films"
    case videoGames = "video-games"

    case biography = "biography"
    case women = "women"
    case businessAndEconomics = "business-and-economics"
    case education = "education"
    case foodAndDrink = "food-and-drink"
    case history = "history"
    case militaryAndWarfare = "military-and-warfare"
    case philosophyAndReligion = "philosophy-and-religion"
    case politicsAndGovernment = "politics-and-government"
    case society = "society"
    case transportation = "transportation"

    case biology = "biology"
    case chemistry = "chemistry"
    case internetCulture = "internet-culture"
    case geographical = "geographical"
    case engineering = "engineering"
    case stem = "stem"
    case mathematics = "mathematics"
    case medicineAndHealth = "medicine-and-health"
    case physics = "physics"
    case technology = "technology"

    case africa = "africa"
    case asia = "asia"
    case centralAmerica = "central-america"
    case europe = "europe"
    case northAmerica = "north-america"
    case oceania = "oceania"
    case southAmerica = "south-america"
}
