# Checks that the PR has a label beginning with "Release-" (e.g. "Release-2027.01.01").
# This is to prevent unwanted PRs from being merged into main.
name: Check PR and App Versions

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - 'main'

jobs:
  check-version:
    runs-on: macos-26
    steps:
    - name: Check PR label for Release- prefix
      continue-on-error: false
      run: |
        PRLABELS='${{ toJson(github.event.pull_request.labels.*.name) }}'

        MATCH_FOUND=false

        echo "PR Labels: $PRLABELS"

        for LABEL in $(echo "$PRLABELS" | jq -r '.[]'); do
          if [[ "$LABEL" == Release-* ]]; then
            MATCH_FOUND=true
            echo "Match found: '$LABEL' begins with 'Release-'"
            break
          fi
        done

        if [ "$MATCH_FOUND" != "true" ]; then
          echo "Error: No PR label beginning with 'Release-' was found."
          exit 1
        fi

        echo "Success: A Release- label is present on this PR."
